version: '3'

services:
  web: &web
    image: as_email_service_app
    container_name: app
    build:
      context: .
      dockerfile: ./Dockerfile
      target: app
    depends_on:
      - mailhog
    ports:
      - "8000:11578"
    command: /app/scripts/start_app.sh
    restart: always
    env_file: .env
    volumes:
      - ./app:/app:z
      - ./dbs:/mnt/db:z

  smtpd:
    <<: *web
    build:
      target: smtpd
    image: as_email_service_smtpd
    container_name: smtpd
    ports:
      - "19246:586"
    command: wait-for-it --service app:8000 -- /app/scripts/start_smtpd.sh
    restart: always
    env_file: .env
    volumes:
      - ./app:/app:z
      - ./dbs:/mnt/db:z
      - ./spool:/mnt/spool:z
      - ./ssl:/mnt/ssl:ro

  worker:
    <<: *web
    build:
      target: worker
    image: as_email_service_worker
    container_name: worker
    ports:
      - "19246:586"
    command: wait-for-it --service app:8000 -- /app/scripts/start_worker.sh
    restart: always
    env_file: .env
    volumes:
      - ./app:/app:z
      - ./dbs:/mnt/db:z
      - ./spool:/mnt/spool:z

  mailhog:
    image: druidfi/mailhog:1.0.1
    container_name: mailhog
    ports:
      - "8025:8025"
