version: '3'

services:
  web: &web
    image: as_email_service_app
    container_name: app
    build:
      context: .
      dockerfile: ./Dockerfile
      target: prod
    ports:
      - "8000:11578"
    command: /app/scripts/start_app.sh
    restart: always
    env_file: .env
    volumes:
      - ./app:/app:z
      - ./dbs:/mnt/db:z
    profiles:
      - prod

  devweb:
    <<: *web
    image: as_email_service_app_dev
    container_name: app_dev
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    depends_on:
      - mailhog
    ports:
      - "8000:11578"
    command: /app/scripts/start_app.sh
    restart: always
    env_file: .env
    volumes:
      - ./app:/app:z
      - ./dbs:/mnt/db:z
    profiles:
      - dev

  smtpd:
    <<: *web
    build:
      target: prod
    image: as_email_service_app
    container_name: smtpd
    ports:
      - "19246:586"
    command: /app/scripts/start_smtpd.sh
    restart: always
    env_file: .env
    volumes:
      - ./app:/app:z
      - ./dbs:/mnt/db:z
      - ./spool:/mnt/spool:z
      - ./ssl:/mnt/ssl:ro
    profiles:
      - dev
      - prod

  worker:
    <<: *web
    build:
      target: prod
    image: as_email_service_app
    container_name: worker
    ports:
      - "19247:586"
    command: /app/scripts/start_worker.sh
    restart: always
    env_file: .env
    volumes:
      - ./app:/app:z
      - ./dbs:/mnt/db:z
      - ./spool:/mnt/spool:z
    profiles:
      - dev
      - prod

  mailhog:
    image: druidfi/mailhog:1.0.1
    container_name: mailhog
    ports:
      - "8025:8025"
    profiles:
      - dev
