[tool.black]
line-length = 88

[tool.isort]
atomic = true
profile = "black"
line_length = 88
skip_gitignore = true
# skip_glob = ["src/blib2to3", "tests/data", "profiling"]
# known_first_party = ["black", "blib2to3", "blackd", "_black_version"]

[tool.ruff]
line-length = 88
exclude = [
    'migrations/.+\.py$',
]

[tool.mypy]
exclude = [
    'migrations/.+\.py$',
]
plugins = ["mypy_django_plugin.main"]

[tool.django-stubs]
django_settings_module = "as_email_service.as_email_service.settings"
ignore_missing_model_attributes = true

[tool.mypy_django_plugin]
ignore_missing_model_attributes = true
